[008] - Homework 8 - Streams and Lambdas
yalenna/ElenaIaropolova pull request #18
Opened 2023-04-25 22:42 UTC by yalenna

2023-04-26 12:05 UTC, tintinfairy requested changes

2023-04-26 14:21 UTC, yalenna commented on src/homework8/Task1.java
> +        try (BufferedWriter writer = new BufferedWriter(new FileWriter("./src/Homework7/Resources/output.txt"))) {
I replaced resources package to `src` directory. Also I'll update paths in previous HW7. Also updated paths in Tasks 1, 2, 4, 5.

2023-04-26 14:22 UTC, yalenna commented on src/homework8/Task8.java
> +interface SumFunction {
Added.

2023-04-26 14:22 UTC, yalenna commented on src/homework8/Task9.java
> +interface NumberDivisibleBy31 {
Done.

2023-04-26 14:23 UTC, yalenna commented on src/homework8/Task7.java
> +package homework8;
Done.

2023-04-27 16:00 UTC, tintinfairy commented on src/homework8/Task4.java
> +    public static void main(String[] args) throws IOException {
FYI `throws` is not necessary here, cause you have a catch block.

2023-04-27 16:02 UTC, tintinfairy commented
Well done!
This PR can be merged.

2023-04-27 16:02 UTC, tintinfairy approved these changes

2023-04-27 16:30 UTC, merged